---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 1
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
        - name: wildfly
          image: localhost:5000/esl:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/jboss/wildfly/standalone/deployments
              name: deployments
      volumes:
        - name: deployments
          hostPath:
            path: /home/wildfly/2022-03-28/deployments
