---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly
spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 1
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
        - name: wildfly
          image: localhost:5000/esl:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/jboss/wildfly/standalone/deployments
              name: deployments
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
      volumes:
        - name: deployments
          hostPath:
            path: /home/wildfly/deployments
