---
apiVersion: v1
kind: Service
metadata:
  name: wildfly
  labels:
    name: wildfly
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: wildfly
  type: NodePort