apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotations:
        checksum/config: {{ include (print $.Template.BasePath "/postgres-configmap.yml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.network.port }}
          volumeMounts:
            - mountPath: /opt/jboss/{{ .Values.name }}/standalone/deployments
              name: deployments
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-conf
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-conf
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.name }}-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-credentials
                  key: postgres_password
      volumes:
        - name: deployments
          hostPath:
            path: {{ .Values.mountpoint }}
