apiVersion: v1
kind: Service
metadata:
  name: wildfly
  labels:
    name: wildfly
  namespace: wf
  resourceVersion: "123"
spec:
  ports:
    - port: 1080
      targetPort: 1080
      nodePort: 30007
  selector:
    app: wildfly
  type: NodePort
